language: python
python: 3.7
install:
  - pip install tox
env:
  - TOXENV=py27-django1.4
  - TOXENV=py27-django1.7
  - TOXENV=py27-django1.8
  - TOXENV=py37-django1.7
  - TOXENV=py37-django1.8
script:
  - tox -e $TOXENV
